name: crispr_identify_env
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - _py-xgboost-mutex=2.0=cpu_0
  - _tflow_select=2.3.0=eigen
  - absl-py=0.11.0=py37h06a4308_0
  - aiohttp=3.6.3=py37h7b6447c_0
  - astunparse=1.6.3=py_0
  - async-timeout=3.0.1=py37_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - biopython=1.76=py37h516909a_0
  - blinker=1.4=py37_0
  - brotlipy=0.7.0=py37hb5d75c8_1001
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2020.12.8=h06a4308_0
  - cachetools=4.1.1=py_0
  - certifi=2020.12.5=py37h06a4308_0
  - cffi=1.14.4=py37hc58025e_1
  - chardet=3.0.4=py37he5f6b98_1008
  - click=7.1.2=py_0
  - cryptography=3.1=py37hb09aad4_0
  - cycler=0.10.0=py_2
  - dbus=1.13.6=he372182_0
  - decorator=4.4.2=py_0
  - dill=0.3.3=pyhd8ed1ab_0
  - expat=2.2.9=he1b5a44_2
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.2=he06d7ca_0
  - gast=0.3.3=py_0
  - glib=2.65.0=h3eb4bd4_0
  - google-auth=1.23.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.2=pyhd3eb1b0_2
  - google-pasta=0.2.0=py_0
  - grpcio=1.31.0=py37hf8bcb03_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - h5py=2.10.0=py37hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - hmmer=3.3=he1b5a44_1
  - icu=58.2=hf484d3e_1000
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=2.0.0=py_1
  - joblib=0.14.1=pyh9f0ad1d_0
  - jpeg=9d=h516909a_0
  - keras=2.4.3=0
  - keras-base=2.4.3=py_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.2.0=py37h99015e2_0
  - ld_impl_linux-64=2.34=hc38a660_9
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libffi=3.3=he6710b0_2
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.3.0=h24d8f2e_15
  - libgfortran-ng=7.5.0=hdf63c60_15
  - libgomp=9.3.0=h24d8f2e_15
  - libiconv=1.15=h516909a_1006
  - liblapack=3.8.0=17_openblas
  - libopenblas=0.3.10=pthreads_hb3c22a3_4
  - libpng=1.6.37=hed695b0_2
  - libprotobuf=3.13.0.1=hd408876_0
  - libstdcxx-ng=9.3.0=hdf63c60_15
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxgboost=1.2.0=he1b5a44_0
  - libxml2=2.9.9=h13577e0_2
  - markdown=3.3.3=py37h06a4308_0
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37hef1b27d_0
  - multidict=4.7.6=py37h7b6447c_1
  - ncurses=6.2=he1b5a44_1
  - networkx=2.5=py_0
  - numpy=1.18.1=py37h8960a57_1
  - oauthlib=3.1.0=py_0
  - openjdk=8.0.152=h7b6447c_3
  - openssl=1.1.1i=h27cfd23_0
  - opt_einsum=3.1.0=py_0
  - pandas=1.0.3=py37h0da4684_1
  - pcre=8.44=he1b5a44_0
  - perl=5.26.2=h14c3975_0
  - perl-bioperl=1.6.924=4
  - perl-biox-seq=0.006007=pl526_1
  - perl-compress-bgzf=0.005=pl526_0
  - perl-file-which=1.23=pl526_0
  - perl-threaded=5.26.0=0
  - perl-yaml=1.29=pl526_0
  - pip=20.2.2=py_0
  - prodigal=2.6.3=h516909a_2
  - protobuf=3.13.0.1=py37he6710b0_1
  - pthread-stubs=0.4=h14c3975_1001
  - py-xgboost=1.2.0=py37hc8dfbb8_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyjwt=1.7.1=py37_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.9.2=py37hcca6a23_4
  - pysocks=1.7.1=py37he5f6b98_2
  - python=3.7.7=hcff3b4d_5
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=pyh9f0ad1d_0
  - pyyaml=5.3.1=py37h7b6447c_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=he28a2e2_2
  - regex=2019.03.09=py37h14c3975_0
  - requests=2.25.0=pyhd3deb0d_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.6=py_0
  - scikit-learn=0.22.1=py37hcdab131_1
  - scipy=1.4.1=py37ha3d9a3c_3
  - setuptools=49.6.0=py37hc8dfbb8_0
  - sip=4.19.8=py37hf484d3e_1000
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.32.3=h4cf870e_1
  - tensorboard=2.3.0=pyh4dce500_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.3.0=eigen_py37h189e6a2_0
  - tensorflow-base=2.3.0=eigen_py37h3b305d7_0
  - tensorflow-estimator=2.3.0=pyheb71bc4_0
  - termcolor=1.1.0=py37_1
  - tk=8.6.10=hed695b0_0
  - tornado=6.0.4=py37h8f50634_1
  - urllib3=1.25.11=py_0
  - viennarna=2.4.15=py37h13b99d1_0
  - werkzeug=1.0.1=py_0
  - wheel=0.35.1=pyh9f0ad1d_0
  - wrapt=1.12.1=py37h7b6447c_1
  - xgboost=1.2.0=py37h3340039_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.6.2=py37h7b6447c_0
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h516909a_1007