name: crispr_identifier_cas_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=openblas
  - ca-certificates=2020.4.5.1=hecc5488_0
  - certifi=2020.4.5.1=py37hc8dfbb8_0
  - hmmer=3.2.1=he1b5a44_2
  - joblib=0.14.1=py_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libopenblas=0.3.6=h5a2b251_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_0
  - nomkl=3.0=0
  - numpy=1.17.4=py37hd5be1e1_0
  - numpy-base=1.17.4=py37h2f8d375_0
  - openssl=1.1.1f=h516909a_0
  - pandas=0.25.3=py37he6710b0_0
  - pip=20.0.2=py37_1
  - prodigal=2.6.3=h516909a_2
  - python=3.7.6=h0371630_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2019.3=py_0
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.22.1=py37h22eb022_0
  - scipy=1.3.2=py37he2b7bc3_0
  - setuptools=46.1.3=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.34.2=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - networkx
  - dill
  - requests
  - toolz
  - regex=2019.03.09
  - joblib




